# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupschedule',
            name='sched_rep',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
