# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0002_auto_20170202_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
            ],
        ),
    ]
