# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-06 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0002_meetupschedule_sched_rep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetupschedule',
            name='sched_rep',
        ),
    ]
