# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0003_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_id', models.IntegerField()),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('start_hour', models.IntegerField()),
                ('start_minute', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('end_minute', models.IntegerField()),
            ],
        ),
    ]
