# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0003_remove_meetupschedule_sched_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetuprequest',
            name='is_attending',
            field=models.IntegerField(default=0),
        ),
    ]
