# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-04 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0005_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupschedule',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
