# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-04 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0006_meetupschedule_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetup_schedule_id', models.IntegerField()),
                ('member_id', models.IntegerField()),
            ],
        ),
    ]
