# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-04 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0007_meetuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetuprequest',
            name='is_attending',
            field=models.BooleanField(default=False),
        ),
    ]
